/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const appRouter: typeof import('./src/utils/router/index')['appRouter']
  const applyTheme: typeof import('./src/composables/useTheme')['applyTheme']
  const avatarGroupInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['avatarGroupInjectionKey']
  const buttonGroupInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup.js')['buttonGroupInjectionKey']
  const defineLocale: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale.js')['defineLocale']
  const defineShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['defineShortcuts']
  const extractShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['extractShortcuts']
  const formBusInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formBusInjectionKey']
  const formFieldInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formFieldInjectionKey']
  const formInputsInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formInputsInjectionKey']
  const formLoadingInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formLoadingInjectionKey']
  const formOptionsInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formOptionsInjectionKey']
  const i18n: typeof import('./src/utils/i18n')['i18n']
  const inputIdInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['inputIdInjectionKey']
  const kbdKeysMap: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['kbdKeysMap']
  const localeContextInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js')['localeContextInjectionKey']
  const notivue: typeof import('./src/utils/notifications')['notivue']
  const pinia: typeof import('./src/utils/pinia')['pinia']
  const useAppConfig: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js')['useAppConfig']
  const useAvatarGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['useAvatarGroup']
  const useBrowserLocalStorage: typeof import('./src/composables/useBrowserStorage')['useBrowserLocalStorage']
  const useBrowserSyncStorage: typeof import('./src/composables/useBrowserStorage')['useBrowserSyncStorage']
  const useButtonGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup.js')['useButtonGroup']
  const useComponentIcons: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.js')['useComponentIcons']
  const useFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['useFormField']
  const useKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['useKbd']
  const useLocale: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js')['useLocale']
  const useOptionsStore: typeof import('./src/stores/options.store')['useOptionsStore']
  const useOverlay: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.js')['useOverlay']
  const useTestStore: typeof import('./src/stores/test.store')['useTestStore']
  const useTheme: typeof import('./src/composables/useTheme')['useTheme']
  const useToast: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useToast.js')['useToast']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ShortcutConfig, ShortcutsConfig, ShortcutsOptions } from './node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d'
  import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d')
  // @ts-ignore
  export type { UseComponentIconsProps } from './node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d'
  import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d')
  // @ts-ignore
  export type { KbdKey, KbdKeySpecific } from './node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d'
  import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d')
  // @ts-ignore
  export type { OverlayOptions, Overlay } from './node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.d'
  import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.d')
  // @ts-ignore
  export type { Toast } from './node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useToast.d'
  import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/composables/useToast.d')
}
