/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DisplayError: typeof import('./src/components/state/DisplayError.vue')['default']
    LoadingSpinner: typeof import('./src/components/state/LoadingSpinner.vue')['default']
    LocaleSwitch: typeof import('./src/components/LocaleSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./src/components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./src/components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.26.7_embla-carousel@8.5.2_typescript@5.8.2_vite@6.2.2_@t_935c1ad832996e9732408cbe10a10746/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
