/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhListHeart: typeof import('~icons/ph/list-heart')['default']
    IPhPresentationChart: typeof import('~icons/ph/presentation-chart')['default']
    IPhRocketLaunch: typeof import('~icons/ph/rocket-launch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
