/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
